<?php

declare(strict_types=1);

/**
 * Coefficient Uw (fenêtre complète : vitrage + menuiserie) en W/(m².K) — §3.3.2 p.26-29.
 *
 * Digitalisation **complète** des 4 tableaux de la spec, indexée par
 * `[type_menuiserie][ug_str][type_baie]`.
 *
 *   - type_menuiserie : 'metal_rpt' | 'metal_sans_rpt' | 'pvc' | 'bois'
 *   - ug_str : clé string (ex '0.5', '2.6') pour préserver les décimales (PHP convertit les floats en int)
 *   - type_baie : 'battante' | 'coulissante' | 'pf_battante' | 'pf_coulissante' | 'pf_battante_soubassement'
 *
 * Pour les Ug intermédiaires : interpolation linéaire (cf. spec § 3.3.2 introduction).
 *
 * @spec-section 3.3.2
 * @spec-pages 26-29
 * @spec-source resources/specsplitted/03-enveloppe-deperditions/03-parois-vitrees-portes/02-uw/00-calcul.md
 * @generated-on 2026-04-29
 */
return [
    'metal_rpt' => [
        '0.5' => ['battante' => 1.3, 'coulissante' => 1.4, 'pf_battante' => 1, 'pf_coulissante' => 1.2],
        '0.6' => ['battante' => 1.4, 'coulissante' => 1.5, 'pf_battante' => 1.1, 'pf_coulissante' => 1.3],
        '0.7' => ['battante' => 1.5, 'coulissante' => 1.6, 'pf_battante' => 1.2, 'pf_coulissante' => 1.4],
        '0.8' => ['battante' => 1.6, 'coulissante' => 1.6, 'pf_battante' => 1.3, 'pf_coulissante' => 1.5],
        '0.9' => ['battante' => 1.6, 'coulissante' => 1.7, 'pf_battante' => 1.4, 'pf_coulissante' => 1.6],
        '1' => ['battante' => 1.7, 'coulissante' => 1.8, 'pf_battante' => 1.5, 'pf_coulissante' => 1.6],
        '1.1' => ['battante' => 1.8, 'coulissante' => 1.9, 'pf_battante' => 1.6, 'pf_coulissante' => 1.7],
        '1.2' => ['battante' => 1.9, 'coulissante' => 2, 'pf_battante' => 1.7, 'pf_coulissante' => 1.8],
        '1.3' => ['battante' => 2, 'coulissante' => 2, 'pf_battante' => 1.7, 'pf_coulissante' => 1.9],
        '1.4' => ['battante' => 2.1, 'coulissante' => 2.1, 'pf_battante' => 1.8, 'pf_coulissante' => 2],
        '1.5' => ['battante' => 2.1, 'coulissante' => 2.2, 'pf_battante' => 1.9, 'pf_coulissante' => 2.1],
        '1.6' => ['battante' => 2.2, 'coulissante' => 2.3, 'pf_battante' => 2, 'pf_coulissante' => 2.2],
        '1.7' => ['battante' => 2.3, 'coulissante' => 2.4, 'pf_battante' => 2.1, 'pf_coulissante' => 2.3],
        '1.8' => ['battante' => 2.4, 'coulissante' => 2.4, 'pf_battante' => 2.2, 'pf_coulissante' => 2.4],
        '1.9' => ['battante' => 2.5, 'coulissante' => 2.5, 'pf_battante' => 2.3, 'pf_coulissante' => 2.5],
        '2' => ['battante' => 2.6, 'coulissante' => 2.6, 'pf_battante' => 2.4, 'pf_coulissante' => 2.5],
        '2.1' => ['battante' => 2.7, 'coulissante' => 2.8, 'pf_battante' => 2.5, 'pf_coulissante' => 2.6],
        '2.2' => ['battante' => 2.7, 'coulissante' => 2.9, 'pf_battante' => 2.6, 'pf_coulissante' => 2.7],
        '2.3' => ['battante' => 2.8, 'coulissante' => 2.9, 'pf_battante' => 2.6, 'pf_coulissante' => 2.8],
        '2.4' => ['battante' => 2.9, 'coulissante' => 3, 'pf_battante' => 2.7, 'pf_coulissante' => 2.9],
        '2.5' => ['battante' => 3, 'coulissante' => 3.1, 'pf_battante' => 2.8, 'pf_coulissante' => 3],
        '2.6' => ['battante' => 3.1, 'coulissante' => 3.2, 'pf_battante' => 2.9, 'pf_coulissante' => 3.1],
        '2.7' => ['battante' => 3.2, 'coulissante' => 3.3, 'pf_battante' => 3, 'pf_coulissante' => 3.2],
        '2.8' => ['battante' => 3.3, 'coulissante' => 3.3, 'pf_battante' => 3.1, 'pf_coulissante' => 3.3],
        '2.9' => ['battante' => 3.3, 'coulissante' => 3.4, 'pf_battante' => 3.2, 'pf_coulissante' => 3.4],
        '3' => ['battante' => 3.4, 'coulissante' => 3.5, 'pf_battante' => 3.3, 'pf_coulissante' => 3.4],
        '3.1' => ['battante' => 3.5, 'coulissante' => 3.6, 'pf_battante' => 3.4, 'pf_coulissante' => 3.5],
        '3.2' => ['battante' => 3.6, 'coulissante' => 3.7, 'pf_battante' => 3.5, 'pf_coulissante' => 3.6],
        '3.3' => ['battante' => 3.7, 'coulissante' => 3.7, 'pf_battante' => 3.5, 'pf_coulissante' => 3.7],
        '3.4' => ['battante' => 3.8, 'coulissante' => 3.8, 'pf_battante' => 3.6, 'pf_coulissante' => 3.8],
        '3.5' => ['battante' => 3.8, 'coulissante' => 3.9, 'pf_battante' => 3.7, 'pf_coulissante' => 3.9],
        '3.6' => ['battante' => 3.9, 'coulissante' => 4, 'pf_battante' => 3.8, 'pf_coulissante' => 3.9],
        '3.7' => ['battante' => 4, 'coulissante' => 4.1, 'pf_battante' => 3.9, 'pf_coulissante' => 4.1],
        '3.8' => ['battante' => 4.1, 'coulissante' => 4.1, 'pf_battante' => 4, 'pf_coulissante' => 4.2],
        '3.9' => ['battante' => 4.2, 'coulissante' => 4.2, 'pf_battante' => 4.1, 'pf_coulissante' => 4.3],
        '4' => ['battante' => 4.3, 'coulissante' => 4.3, 'pf_battante' => 4.2, 'pf_coulissante' => 4.3],
        '5.7' => ['battante' => 5.7, 'coulissante' => 5.7, 'pf_battante' => 5.7, 'pf_coulissante' => 5.8],
        '5.8' => ['battante' => 5.8, 'coulissante' => 5.8, 'pf_battante' => 5.8, 'pf_coulissante' => 5.9],
        '5.9' => ['battante' => 5.9, 'coulissante' => 5.9, 'pf_battante' => 5.9, 'pf_coulissante' => 6],
        '6' => ['battante' => 6, 'coulissante' => 6, 'pf_battante' => 6, 'pf_coulissante' => 6.1],
    ],
    'metal_sans_rpt' => [
        '0.5' => ['battante' => 1.9, 'coulissante' => 2.2, 'pf_battante' => 1.4, 'pf_coulissante' => 1.5],
        '0.6' => ['battante' => 2, 'coulissante' => 2.3, 'pf_battante' => 1.5, 'pf_coulissante' => 1.6],
        '0.7' => ['battante' => 2.1, 'coulissante' => 2.4, 'pf_battante' => 1.6, 'pf_coulissante' => 1.7],
        '0.8' => ['battante' => 2.2, 'coulissante' => 2.4, 'pf_battante' => 1.7, 'pf_coulissante' => 1.8],
        '0.9' => ['battante' => 2.2, 'coulissante' => 2.5, 'pf_battante' => 1.8, 'pf_coulissante' => 1.9],
        '1' => ['battante' => 2.3, 'coulissante' => 2.6, 'pf_battante' => 1.9, 'pf_coulissante' => 1.9],
        '1.1' => ['battante' => 2.4, 'coulissante' => 2.7, 'pf_battante' => 2, 'pf_coulissante' => 2],
        '1.2' => ['battante' => 2.5, 'coulissante' => 2.8, 'pf_battante' => 2.1, 'pf_coulissante' => 2.1],
        '1.3' => ['battante' => 2.6, 'coulissante' => 2.8, 'pf_battante' => 2.1, 'pf_coulissante' => 2.2],
        '1.4' => ['battante' => 2.7, 'coulissante' => 2.9, 'pf_battante' => 2.2, 'pf_coulissante' => 2.3],
        '1.5' => ['battante' => 2.7, 'coulissante' => 3, 'pf_battante' => 2.3, 'pf_coulissante' => 2.4],
        '1.6' => ['battante' => 2.8, 'coulissante' => 3.1, 'pf_battante' => 2.4, 'pf_coulissante' => 2.5],
        '1.7' => ['battante' => 2.9, 'coulissante' => 3.2, 'pf_battante' => 2.5, 'pf_coulissante' => 2.6],
        '1.8' => ['battante' => 3, 'coulissante' => 3.2, 'pf_battante' => 2.6, 'pf_coulissante' => 2.7],
        '1.9' => ['battante' => 3.1, 'coulissante' => 3.3, 'pf_battante' => 2.7, 'pf_coulissante' => 2.8],
        '2' => ['battante' => 3.2, 'coulissante' => 3.4, 'pf_battante' => 2.8, 'pf_coulissante' => 2.8],
        '2.1' => ['battante' => 3.3, 'coulissante' => 3.5, 'pf_battante' => 2.9, 'pf_coulissante' => 2.9],
        '2.2' => ['battante' => 3.3, 'coulissante' => 3.6, 'pf_battante' => 3, 'pf_coulissante' => 3],
        '2.3' => ['battante' => 3.4, 'coulissante' => 3.6, 'pf_battante' => 3, 'pf_coulissante' => 3.1],
        '2.4' => ['battante' => 3.5, 'coulissante' => 3.7, 'pf_battante' => 3.1, 'pf_coulissante' => 3.2],
        '2.5' => ['battante' => 3.6, 'coulissante' => 3.8, 'pf_battante' => 3.2, 'pf_coulissante' => 3.3],
        '2.6' => ['battante' => 3.7, 'coulissante' => 3.9, 'pf_battante' => 3.3, 'pf_coulissante' => 3.4],
        '2.7' => ['battante' => 3.8, 'coulissante' => 4, 'pf_battante' => 3.4, 'pf_coulissante' => 3.5],
        '2.8' => ['battante' => 3.9, 'coulissante' => 4, 'pf_battante' => 3.5, 'pf_coulissante' => 3.6],
        '2.9' => ['battante' => 3.9, 'coulissante' => 4.1, 'pf_battante' => 3.6, 'pf_coulissante' => 3.7],
        '3' => ['battante' => 4, 'coulissante' => 4.2, 'pf_battante' => 3.7, 'pf_coulissante' => 3.7],
        '3.1' => ['battante' => 4.1, 'coulissante' => 4.3, 'pf_battante' => 3.8, 'pf_coulissante' => 3.8],
        '3.2' => ['battante' => 4.2, 'coulissante' => 4.4, 'pf_battante' => 3.9, 'pf_coulissante' => 3.9],
        '3.3' => ['battante' => 4.3, 'coulissante' => 4.4, 'pf_battante' => 3.9, 'pf_coulissante' => 4],
        '3.4' => ['battante' => 4.4, 'coulissante' => 4.5, 'pf_battante' => 4, 'pf_coulissante' => 4.1],
        '3.5' => ['battante' => 4.4, 'coulissante' => 4.6, 'pf_battante' => 4.1, 'pf_coulissante' => 4.2],
        '3.6' => ['battante' => 4.5, 'coulissante' => 4.7, 'pf_battante' => 4.2, 'pf_coulissante' => 4.3],
        '3.7' => ['battante' => 4.6, 'coulissante' => 4.8, 'pf_battante' => 4.3, 'pf_coulissante' => 4.4],
        '3.8' => ['battante' => 4.7, 'coulissante' => 4.8, 'pf_battante' => 4.4, 'pf_coulissante' => 4.5],
        '3.9' => ['battante' => 4.8, 'coulissante' => 4.9, 'pf_battante' => 4.5, 'pf_coulissante' => 4.6],
        '4' => ['battante' => 4.9, 'coulissante' => 5, 'pf_battante' => 4.6, 'pf_coulissante' => 4.6],
        '5.7' => ['battante' => 6.3, 'coulissante' => 6.4, 'pf_battante' => 6.1, 'pf_coulissante' => 6.2],
        '5.8' => ['battante' => 6.4, 'coulissante' => 6.4, 'pf_battante' => 6.2, 'pf_coulissante' => 6.3],
        '5.9' => ['battante' => 6.5, 'coulissante' => 6.5, 'pf_battante' => 6.3, 'pf_coulissante' => 6.4],
        '6' => ['battante' => 6.6, 'coulissante' => 6.6, 'pf_battante' => 6.4, 'pf_coulissante' => 6.4],
    ],
    'pvc' => [
        '0.5' => ['battante' => 0.9, 'coulissante' => 1.3, 'pf_battante' => 0.8, 'pf_coulissante' => 1.1, 'pf_battante_soubassement' => 0.9],
        '0.6' => ['battante' => 1, 'coulissante' => 1.4, 'pf_battante' => 0.9, 'pf_coulissante' => 1.2, 'pf_battante_soubassement' => 1],
        '0.7' => ['battante' => 1.1, 'coulissante' => 1.5, 'pf_battante' => 1, 'pf_coulissante' => 1.2, 'pf_battante_soubassement' => 1.1],
        '0.8' => ['battante' => 1.2, 'coulissante' => 1.5, 'pf_battante' => 1, 'pf_coulissante' => 1.3, 'pf_battante_soubassement' => 1.1],
        '0.9' => ['battante' => 1.2, 'coulissante' => 1.6, 'pf_battante' => 1.1, 'pf_coulissante' => 1.4, 'pf_battante_soubassement' => 1.2],
        '1' => ['battante' => 1.3, 'coulissante' => 1.7, 'pf_battante' => 1.2, 'pf_coulissante' => 1.5, 'pf_battante_soubassement' => 1.3],
        '1.1' => ['battante' => 1.4, 'coulissante' => 1.7, 'pf_battante' => 1.3, 'pf_coulissante' => 1.6, 'pf_battante_soubassement' => 1.4],
        '1.2' => ['battante' => 1.5, 'coulissante' => 1.8, 'pf_battante' => 1.4, 'pf_coulissante' => 1.6, 'pf_battante_soubassement' => 1.4],
        '1.3' => ['battante' => 1.5, 'coulissante' => 1.9, 'pf_battante' => 1.4, 'pf_coulissante' => 1.7, 'pf_battante_soubassement' => 1.5],
        '1.4' => ['battante' => 1.6, 'coulissante' => 2, 'pf_battante' => 1.5, 'pf_coulissante' => 1.8, 'pf_battante_soubassement' => 1.6],
        '1.5' => ['battante' => 1.7, 'coulissante' => 2, 'pf_battante' => 1.6, 'pf_coulissante' => 1.9, 'pf_battante_soubassement' => 1.6],
        '1.6' => ['battante' => 1.8, 'coulissante' => 2.1, 'pf_battante' => 1.7, 'pf_coulissante' => 2, 'pf_battante_soubassement' => 1.7],
        '1.7' => ['battante' => 1.8, 'coulissante' => 2.2, 'pf_battante' => 1.8, 'pf_coulissante' => 2, 'pf_battante_soubassement' => 1.8],
        '1.8' => ['battante' => 1.9, 'coulissante' => 2.2, 'pf_battante' => 1.8, 'pf_coulissante' => 2.1, 'pf_battante_soubassement' => 1.8],
        '1.9' => ['battante' => 2, 'coulissante' => 2.3, 'pf_battante' => 1.9, 'pf_coulissante' => 2.2, 'pf_battante_soubassement' => 1.9],
        '2' => ['battante' => 2.1, 'coulissante' => 2.4, 'pf_battante' => 2, 'pf_coulissante' => 2.3, 'pf_battante_soubassement' => 2],
        '2.1' => ['battante' => 2.1, 'coulissante' => 2.4, 'pf_battante' => 2.1, 'pf_coulissante' => 2.4, 'pf_battante_soubassement' => 2.1],
        '2.2' => ['battante' => 2.2, 'coulissante' => 2.5, 'pf_battante' => 2.2, 'pf_coulissante' => 2.4, 'pf_battante_soubassement' => 2.1],
        '2.3' => ['battante' => 2.3, 'coulissante' => 2.6, 'pf_battante' => 2.2, 'pf_coulissante' => 2.5, 'pf_battante_soubassement' => 2.2],
        '2.4' => ['battante' => 2.4, 'coulissante' => 2.7, 'pf_battante' => 2.3, 'pf_coulissante' => 2.6, 'pf_battante_soubassement' => 2.3],
        '2.5' => ['battante' => 2.4, 'coulissante' => 2.7, 'pf_battante' => 2.4, 'pf_coulissante' => 2.7, 'pf_battante_soubassement' => 2.3],
        '2.6' => ['battante' => 2.5, 'coulissante' => 2.8, 'pf_battante' => 2.5, 'pf_coulissante' => 2.8, 'pf_battante_soubassement' => 2.4],
        '2.7' => ['battante' => 2.6, 'coulissante' => 2.9, 'pf_battante' => 2.6, 'pf_coulissante' => 2.8, 'pf_battante_soubassement' => 2.5],
        '2.8' => ['battante' => 2.7, 'coulissante' => 2.9, 'pf_battante' => 2.6, 'pf_coulissante' => 2.9, 'pf_battante_soubassement' => 2.5],
        '2.9' => ['battante' => 2.7, 'coulissante' => 3, 'pf_battante' => 2.7, 'pf_coulissante' => 3, 'pf_battante_soubassement' => 2.6],
        '3' => ['battante' => 2.8, 'coulissante' => 3.1, 'pf_battante' => 2.8, 'pf_coulissante' => 3.1, 'pf_battante_soubassement' => 2.7],
        '3.1' => ['battante' => 2.9, 'coulissante' => 3.1, 'pf_battante' => 2.9, 'pf_coulissante' => 3.2, 'pf_battante_soubassement' => 2.8],
        '3.2' => ['battante' => 3, 'coulissante' => 3.2, 'pf_battante' => 3, 'pf_coulissante' => 3.2, 'pf_battante_soubassement' => 2.8],
        '3.3' => ['battante' => 3, 'coulissante' => 3.3, 'pf_battante' => 3, 'pf_coulissante' => 3.3, 'pf_battante_soubassement' => 2.9],
        '3.4' => ['battante' => 3.1, 'coulissante' => 3.4, 'pf_battante' => 3.1, 'pf_coulissante' => 3.4, 'pf_battante_soubassement' => 3],
        '3.5' => ['battante' => 3.2, 'coulissante' => 3.4, 'pf_battante' => 3.2, 'pf_coulissante' => 3.5, 'pf_battante_soubassement' => 3],
        '3.6' => ['battante' => 3.3, 'coulissante' => 3.5, 'pf_battante' => 3.3, 'pf_coulissante' => 3.6, 'pf_battante_soubassement' => 3.1],
        '3.7' => ['battante' => 3.3, 'coulissante' => 3.6, 'pf_battante' => 3.4, 'pf_coulissante' => 3.6, 'pf_battante_soubassement' => 3.2],
        '3.8' => ['battante' => 3.4, 'coulissante' => 3.6, 'pf_battante' => 3.4, 'pf_coulissante' => 3.7, 'pf_battante_soubassement' => 3.2],
        '3.9' => ['battante' => 3.5, 'coulissante' => 3.7, 'pf_battante' => 3.5, 'pf_coulissante' => 3.8, 'pf_battante_soubassement' => 3.3],
        '4' => ['battante' => 3.6, 'coulissante' => 3.8, 'pf_battante' => 3.6, 'pf_coulissante' => 3.9, 'pf_battante_soubassement' => 3.4],
        '5.7' => ['battante' => 4.8, 'coulissante' => 5, 'pf_battante' => 5, 'pf_coulissante' => 5.2, 'pf_battante_soubassement' => 4.6],
        '5.8' => ['battante' => 4.9, 'coulissante' => 5, 'pf_battante' => 5, 'pf_coulissante' => 5.3, 'pf_battante_soubassement' => 4.6],
        '5.9' => ['battante' => 5, 'coulissante' => 5.1, 'pf_battante' => 5.1, 'pf_coulissante' => 5.4, 'pf_battante_soubassement' => 4.7],
        '6' => ['battante' => 5.1, 'coulissante' => 5.2, 'pf_battante' => 5.2, 'pf_coulissante' => 5.5, 'pf_battante_soubassement' => 4.8],
    ],
    'bois' => [
        '0.5' => ['battante' => 1.1, 'coulissante' => 1.2, 'pf_battante' => 0.9, 'pf_coulissante' => 1, 'pf_battante_soubassement' => 1.1],
        '0.6' => ['battante' => 1.2, 'coulissante' => 1.3, 'pf_battante' => 1, 'pf_coulissante' => 1.1, 'pf_battante_soubassement' => 1.2],
        '0.7' => ['battante' => 1.3, 'coulissante' => 1.4, 'pf_battante' => 1.1, 'pf_coulissante' => 1.2, 'pf_battante_soubassement' => 1.2],
        '0.8' => ['battante' => 1.4, 'coulissante' => 1.4, 'pf_battante' => 1.2, 'pf_coulissante' => 1.2, 'pf_battante_soubassement' => 1.3],
        '0.9' => ['battante' => 1.4, 'coulissante' => 1.5, 'pf_battante' => 1.2, 'pf_coulissante' => 1.3, 'pf_battante_soubassement' => 1.4],
        '1' => ['battante' => 1.5, 'coulissante' => 1.6, 'pf_battante' => 1.3, 'pf_coulissante' => 1.4, 'pf_battante_soubassement' => 1.4],
        '1.1' => ['battante' => 1.6, 'coulissante' => 1.7, 'pf_battante' => 1.4, 'pf_coulissante' => 1.5, 'pf_battante_soubassement' => 1.5],
        '1.2' => ['battante' => 1.7, 'coulissante' => 1.8, 'pf_battante' => 1.5, 'pf_coulissante' => 1.6, 'pf_battante_soubassement' => 1.6],
        '1.3' => ['battante' => 1.8, 'coulissante' => 1.9, 'pf_battante' => 1.6, 'pf_coulissante' => 1.7, 'pf_battante_soubassement' => 1.7],
        '1.4' => ['battante' => 1.8, 'coulissante' => 2, 'pf_battante' => 1.7, 'pf_coulissante' => 1.7, 'pf_battante_soubassement' => 1.7],
        '1.5' => ['battante' => 1.9, 'coulissante' => 2.1, 'pf_battante' => 1.8, 'pf_coulissante' => 1.8, 'pf_battante_soubassement' => 1.8],
        '1.6' => ['battante' => 2, 'coulissante' => 2.1, 'pf_battante' => 1.8, 'pf_coulissante' => 1.9, 'pf_battante_soubassement' => 1.9],
        '1.7' => ['battante' => 2.1, 'coulissante' => 2.2, 'pf_battante' => 1.9, 'pf_coulissante' => 2, 'pf_battante_soubassement' => 1.9],
        '1.8' => ['battante' => 2.2, 'coulissante' => 2.3, 'pf_battante' => 2, 'pf_coulissante' => 2.1, 'pf_battante_soubassement' => 2],
        '1.9' => ['battante' => 2.2, 'coulissante' => 2.4, 'pf_battante' => 2.1, 'pf_coulissante' => 2.2, 'pf_battante_soubassement' => 2.1],
        '2' => ['battante' => 2.3, 'coulissante' => 2.4, 'pf_battante' => 2.2, 'pf_coulissante' => 2.3, 'pf_battante_soubassement' => 2.1],
        '2.1' => ['battante' => 2.4, 'coulissante' => 2.5, 'pf_battante' => 2.3, 'pf_coulissante' => 2.3, 'pf_battante_soubassement' => 2.2],
        '2.2' => ['battante' => 2.5, 'coulissante' => 2.6, 'pf_battante' => 2.3, 'pf_coulissante' => 2.4, 'pf_battante_soubassement' => 2.3],
        '2.3' => ['battante' => 2.6, 'coulissante' => 2.7, 'pf_battante' => 2.4, 'pf_coulissante' => 2.5, 'pf_battante_soubassement' => 2.4],
        '2.4' => ['battante' => 2.6, 'coulissante' => 2.7, 'pf_battante' => 2.5, 'pf_coulissante' => 2.6, 'pf_battante_soubassement' => 2.4],
        '2.5' => ['battante' => 2.7, 'coulissante' => 2.8, 'pf_battante' => 2.6, 'pf_coulissante' => 2.7, 'pf_battante_soubassement' => 2.5],
        '2.6' => ['battante' => 2.8, 'coulissante' => 2.9, 'pf_battante' => 2.7, 'pf_coulissante' => 2.8, 'pf_battante_soubassement' => 2.6],
        '2.7' => ['battante' => 2.9, 'coulissante' => 3, 'pf_battante' => 2.8, 'pf_coulissante' => 2.9, 'pf_battante_soubassement' => 2.6],
        '2.8' => ['battante' => 3, 'coulissante' => 3, 'pf_battante' => 2.9, 'pf_coulissante' => 2.9, 'pf_battante_soubassement' => 2.7],
        '2.9' => ['battante' => 3, 'coulissante' => 3.1, 'pf_battante' => 2.9, 'pf_coulissante' => 3, 'pf_battante_soubassement' => 2.8],
        '3' => ['battante' => 3.1, 'coulissante' => 3.2, 'pf_battante' => 3, 'pf_coulissante' => 3.1, 'pf_battante_soubassement' => 2.8],
        '3.1' => ['battante' => 3.2, 'coulissante' => 3.3, 'pf_battante' => 3.1, 'pf_coulissante' => 3.2, 'pf_battante_soubassement' => 2.9],
        '3.2' => ['battante' => 3.3, 'coulissante' => 3.3, 'pf_battante' => 3.2, 'pf_coulissante' => 3.3, 'pf_battante_soubassement' => 3],
        '3.3' => ['battante' => 3.4, 'coulissante' => 3.4, 'pf_battante' => 3.3, 'pf_coulissante' => 3.4, 'pf_battante_soubassement' => 3.1],
        '3.4' => ['battante' => 3.4, 'coulissante' => 3.5, 'pf_battante' => 3.4, 'pf_coulissante' => 3.4, 'pf_battante_soubassement' => 3.1],
        '3.5' => ['battante' => 3.5, 'coulissante' => 3.6, 'pf_battante' => 3.5, 'pf_coulissante' => 3.5, 'pf_battante_soubassement' => 3.2],
        '3.6' => ['battante' => 3.6, 'coulissante' => 3.6, 'pf_battante' => 3.5, 'pf_coulissante' => 3.6, 'pf_battante_soubassement' => 3.3],
        '3.7' => ['battante' => 3.7, 'coulissante' => 3.7, 'pf_battante' => 3.6, 'pf_coulissante' => 3.7, 'pf_battante_soubassement' => 3.3],
        '3.8' => ['battante' => 3.8, 'coulissante' => 3.8, 'pf_battante' => 3.7, 'pf_coulissante' => 3.8, 'pf_battante_soubassement' => 3.4],
        '3.9' => ['battante' => 3.8, 'coulissante' => 3.9, 'pf_battante' => 3.8, 'pf_coulissante' => 3.9, 'pf_battante_soubassement' => 3.5],
        '4' => ['battante' => 3.9, 'coulissante' => 3.9, 'pf_battante' => 3.9, 'pf_coulissante' => 4, 'pf_battante_soubassement' => 3.5],
        '5.7' => ['battante' => 5.3, 'coulissante' => 5.3, 'pf_battante' => 5.3, 'pf_coulissante' => 5.4, 'pf_battante_soubassement' => 4.7],
        '5.8' => ['battante' => 5.4, 'coulissante' => 5.4, 'pf_battante' => 5.4, 'pf_coulissante' => 5.5, 'pf_battante_soubassement' => 4.8],
        '5.9' => ['battante' => 5.4, 'coulissante' => 5.4, 'pf_battante' => 5.5, 'pf_coulissante' => 5.6, 'pf_battante_soubassement' => 4.9],
        '6' => ['battante' => 5.5, 'coulissante' => 5.5, 'pf_battante' => 5.6, 'pf_coulissante' => 5.7, 'pf_battante_soubassement' => 4.9],
    ],
];
