<?php

/**
 * Critères de comptage des lignes collectives de la table ADEME tv_intermittence.
 * Source : https://github.com/Open3CL/engine/blob/38dfc9c4156ecc859d74a3157872643677513ff8/src/tv.js
 * Open3CL, licence MIT. Valeurs de la méthode 3CL §8 p.57.
 * Aucun résultat calculé du diagnostic n’est utilisé.
 */
return [
    151 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [5, 42, 46, 47, 48, 49, 50],
        'comptage' => 'absent',
    ],
    152 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [1, 2, 3, 4, 10, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45],
        'comptage' => 'absent',
    ],
    153 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [6, 7, 15, 16, 17, 18, 44],
        'comptage' => 'absent',
    ],
    154 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [8, 9, 11, 12, 13, 14, 43],
        'comptage' => 'absent',
    ],
    155 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [5, 42, 46, 47, 48, 49, 50],
        'comptage' => 'absent',
    ],
    156 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [1, 2, 3, 4, 10, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45],
        'comptage' => 'absent',
    ],
    157 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [6, 7, 15, 16, 17, 18, 44],
        'comptage' => 'absent',
    ],
    158 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [8, 9, 11, 12, 13, 14, 43],
        'comptage' => 'absent',
    ],
    159 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [5, 42, 46, 47, 48, 49, 50],
        'comptage' => 'absent',
    ],
    160 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [1, 2, 3, 4, 10, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45],
        'comptage' => 'absent',
    ],
    161 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [6, 7, 15, 16, 17, 18, 44],
        'comptage' => 'absent',
    ],
    162 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [8, 9, 11, 12, 13, 14, 43],
        'comptage' => 'absent',
    ],
    163 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [5, 42, 46, 47, 48, 49, 50],
        'comptage' => 'absent',
    ],
    164 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [1, 2, 3, 4, 10, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45],
        'comptage' => 'absent',
    ],
    165 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [6, 7, 15, 16, 17, 18, 44],
        'comptage' => 'absent',
    ],
    166 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [8, 9, 11, 12, 13, 14, 43],
        'comptage' => 'absent',
    ],
    167 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [7],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [5, 42, 46, 47, 48, 49, 50],
        'comptage' => 'absent',
    ],
    168 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [7],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [1, 2, 3, 4, 10, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45],
        'comptage' => 'absent',
    ],
    169 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [7],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [6, 7, 15, 16, 17, 18, 44],
        'comptage' => 'absent',
    ],
    170 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [5, 42, 46, 47, 48, 49, 50],
        'comptage' => 'present',
    ],
    171 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [1, 2, 3, 4, 10, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45],
        'comptage' => 'present',
    ],
    172 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [6, 7, 15, 16, 17, 18, 44],
        'comptage' => 'present',
    ],
    173 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [8, 9, 11, 12, 13, 14, 43],
        'comptage' => 'present',
    ],
    174 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [5, 42, 46, 47, 48, 49, 50],
        'comptage' => 'present',
    ],
    175 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [1, 2, 3, 4, 10, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45],
        'comptage' => 'present',
    ],
    176 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [6, 7, 15, 16, 17, 18, 44],
        'comptage' => 'present',
    ],
    177 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [1],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [8, 9, 11, 12, 13, 14, 43],
        'comptage' => 'present',
    ],
    178 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [5, 42, 46, 47, 48, 49, 50],
        'comptage' => 'present',
    ],
    179 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [1, 2, 3, 4, 10, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45],
        'comptage' => 'present',
    ],
    180 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [6, 7, 15, 16, 17, 18, 44],
        'comptage' => 'present',
    ],
    181 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [8, 9, 11, 12, 13, 14, 43],
        'comptage' => 'present',
    ],
    182 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [5, 42, 46, 47, 48, 49, 50],
        'comptage' => 'present',
    ],
    183 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [1, 2, 3, 4, 10, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45],
        'comptage' => 'present',
    ],
    184 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [6, 7, 15, 16, 17, 18, 44],
        'comptage' => 'present',
    ],
    185 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [6],
        'enum_type_regulation_id' => [1],
        'enum_type_emission_distribution_id' => [8, 9, 11, 12, 13, 14, 43],
        'comptage' => 'present',
    ],
    186 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [7],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [5, 42, 46, 47, 48, 49, 50],
        'comptage' => 'present',
    ],
    187 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [7],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [1, 2, 3, 4, 10, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 45],
        'comptage' => 'present',
    ],
    188 => [
        'enum_type_chauffage_id' => [2],
        'enum_equipement_intermittence_id' => [7],
        'enum_type_regulation_id' => [2],
        'enum_type_emission_distribution_id' => [6, 7, 15, 16, 17, 18, 44],
        'comptage' => 'present',
    ],
];
